# Generated by Django 5.0.1 on 2024-02-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_responses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('doctor', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'appointments',
            },
        ),
    ]
