# Generated by Django 5.0.1 on 2024-02-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='email',
        ),
        migrations.AddField(
            model_name='prescription',
            name='address',
            field=models.TextField(default=None),
        ),
    ]
